import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const data=JSON.parse(read('data/portfolio.json'));
test('all 32 Tai product entries present',()=>assert.equal(data.entries.length,32));
test('unique safe routes',()=>{const s=data.entries.map(e=>e.slug);assert.equal(new Set(s).size,s.length);assert.ok(s.every(x=>/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(x)));});
test('legacy product routes retained',()=>{for(const s of ['peakedlabs','protocolrank','shreddify','ai-business-blueprint','alivelongevity','ohio-power-picker','getfoundinchat','ogfixer','aiopsguide','winemakeros','hireagentbuilders','portcoaudit'])assert.ok(data.entries.some(e=>e.slug===s));});
test('only Tai operating responsibility appears as a project',()=>assert.ok(data.entries.every(e=>e.mode==='agent-led')));
test('projection retains only public allowlisted keys',()=>{const k=['id','slug','name','mode','family','publicUrl','valueEvent','definitionStatus'];for(const e of data.entries)assert.deepEqual(Object.keys(e).sort(),k.slice().sort());});
test('only HTTPS registered links',()=>{for(const e of data.entries)if(e.publicUrl){const u=new URL(e.publicUrl);assert.equal(u.protocol,'https:');assert.equal(u.username,'');assert.equal(u.password,'');}});
test('proposed value claims remain labeled',()=>{assert.match(data.notice,/proposed acceptance targets/);assert.ok(data.entries.every(e=>e.valueEvent&&e.definitionStatus));});
test('homepage has no unsupported autonomy claim',()=>assert.doesNotMatch(read('app/page.tsx'),/Full autonomous AI|Zero human code|Live Portfolio Terminal/));
test('cards preserve labeled artwork instead of made-up results',()=>{const s=read('components/venture-card.tsx');assert.doesNotMatch(s,/deployedPages|animate-pulse/);assert.match(s,/legacyArt/);assert.match(s,/not a current product screenshot/);});
test('directory filters expose pressed state',()=>assert.match(read('components/venture-directory.tsx'),/aria-pressed/));
test('journal separates synthetic tests and businesses',()=>assert.match(read('app/journal/page.tsx'),/does not prove/));
test('existing subscribe component remains',()=>assert.match(read('app/page.tsx'),/NewsletterSignupForm/));
test('sitemap derives all product routes and journal',()=>{assert.match(read('app/sitemap.ts'),/ventures.map/);assert.match(read('app/sitemap.ts'),/journal/);});
