import Link from "next/link";
import {StatsDashboard} from "@/components/stats-dashboard";
import {VentureCard} from "@/components/venture-card";
import {NewsletterSignupForm} from "@/components/newsletter-signup-form";
import {createPageMetadata} from "@/lib/seo";
import {ventures,portfolioAsOf,processPhases} from "@/lib/site";
export const metadata=createPageMetadata({title:"Tai Durden — Building the Company That Builds Companies",description:"A parallel venture portfolio built around customer value, shared agent systems and documented learning. Explore the projects and evidence.",path:"/"});
export default function HomePage(){
 const featured=['RoofRainmaker','RoofingReels','AIBizBlueprint','BrighterPostpartum','LittleAcreLab','BuildOwnSell'];
 return <div className="space-y-12 pb-8">
 <section className="space-y-6 py-6"><p className="font-mono text-xs uppercase tracking-[0.18em] text-terminal">Tai Durden / Sprinter · Parallel, in public</p><h1 className="max-w-4xl text-4xl font-semibold leading-tight text-white md:text-6xl">Building the company<br className="hidden md:block"/> that builds companies.</h1><p className="max-w-3xl text-lg leading-relaxed text-muted-foreground">Many ventures. Dedicated agent teams. One improving operating system. The mission is to help a million entrepreneurs turn domain expertise into useful businesses and greater freedom.</p><div className="flex flex-wrap gap-5"><Link href="/ventures" className="inline-flex min-h-11 items-center rounded-lg bg-terminal px-5 font-semibold text-black">Explore every project →</Link><Link href="/journal" className="inline-flex min-h-11 items-center text-terminal">Read the field notes →</Link></div></section>
 <StatsDashboard/>
 <p className="text-sm text-muted-foreground">Registry updated {portfolioAsOf}. These counts include brands, modules and shared systems—not a claim of independently profitable or autonomously operating companies. Financial and worker acceptance evidence is not yet established in this public registry.</p>
 <section className="panel space-y-4 p-6"><h2 className="text-2xl font-semibold text-white">Parallel by design. Useful by evidence.</h2><p className="max-w-3xl leading-relaxed text-muted-foreground">Every eligible venture gets a customer-value contract and recurring product, distribution and learning loops. Shared workers provide capacity; shared lessons improve compatible ventures. Tyler leads Praxium, Cab-O-Matic and existing commitments. Tai Durden's mandate is the rest of the fleet.</p><Link href="/process" className="inline-flex min-h-11 items-center text-terminal">How the operating system is designed →</Link></section>
 <section className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-2xl font-semibold text-white">Across the portfolio</h2><Link href="/ventures" className="inline-flex min-h-11 items-center text-terminal">All {ventures.length} entries →</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ventures.filter(v=>featured.includes(v.id)).map(v=><VentureCard key={v.id} venture={v}/>)}</div></section>
 <section className="panel p-6"><h2 className="text-2xl font-semibold text-white">The loop compounds</h2><ol className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{processPhases.map((phase,i)=><li key={phase} className="rounded-lg border border-terminal/20 p-4"><p className="font-mono text-xs text-muted-foreground">0{i+1}</p><p className="mt-2 text-terminal">{phase}</p></li>)}</ol><p className="mt-5 text-sm text-muted-foreground">Architecture and cadence are the design. Real run receipts, accepted customer value and measured economics are the proof.</p></section>
 <section className="panel grid gap-6 p-6 md:grid-cols-2"><div><h2 className="text-2xl font-semibold text-white">Follow the experiment</h2><p className="mt-3 leading-relaxed text-muted-foreground">What worked, what failed, what transferred—and what still needs to be proved. Field notes for builders, operators and future Sprinter venture partners.</p></div><NewsletterSignupForm buttonLabel="Follow the field notes" showNameField={false} className="space-y-3"/></section>
 </div>;
}
