import Link from "next/link";
import {notFound} from "next/navigation";
import {createPageMetadata} from "@/lib/seo";
import {theses,thesisFor} from "@/lib/taxonomy";
import {VentureDirectory} from "@/components/venture-directory";
type Props={params:Promise<{slug:string}>};
export const dynamicParams=false;
export function generateStaticParams(){return theses.map(({slug})=>({slug}));}
export async function generateMetadata({params}:Props){const {slug}=await params;const t=thesisFor(slug);if(!t)notFound();return createPageMetadata({title:`${t.title} — ${t.subtitle} | Tai Durden`,description:t.promise,path:`/theses/${slug}`});}
export default async function ThesisPage({params}:Props){const {slug}=await params;const t=thesisFor(slug);if(!t)notFound();return <div className="space-y-8 pb-8" data-thesis-page={slug} data-site-revision={process.env.VERCEL_GIT_COMMIT_SHA??"local"}><Link href="/theses" className="inline-flex min-h-11 items-center text-sm text-terminal">← The abundance thesis</Link><header className="max-w-4xl space-y-4"><p className="font-mono text-xs uppercase tracking-widest text-terminal">{t.subtitle}</p><h1 className="text-4xl font-semibold text-white md:text-5xl">{t.title}</h1><p className="text-xl leading-relaxed text-white/90">{t.promise}</p><p className="leading-relaxed text-muted-foreground">{t.description}</p></header><section className="panel grid gap-5 p-6 md:grid-cols-2"><div><h2 className="font-semibold text-white">What would make this useful?</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{t.valueTest}</p></div><div><h2 className="font-semibold text-white">What I am testing</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{t.learnFrom}</p></div><p className="border-t border-white/10 pt-4 text-sm leading-relaxed text-muted-foreground md:col-span-2">{t.boundary}</p></section><h2 className="text-2xl font-semibold text-white">Products putting this belief to work</h2><VentureDirectory key={slug} thesisSlug={slug}/></div>;}
